# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d2b778766f7ab1f1adb4ec5aab4ca539e4a30e25a2ff3ee2f1c7676a2039858304ee4e92042e4e2a3bab67eb0b5da2d2c38a4b9f124187220aa68e94b0a255c

test:
  secret_key_base: dd8536c632917a07b8e6f9b026cf384740e23a488942066f509bbf904969ba7e7c0b23165653c673f7eebdcff0f2eb61409f6233d99343bc7df322784360babe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
